sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t faisaldev79/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true faisaldev79/frontend-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-frontend'
  env: 'dockerfrontend-env'
  bucket_name: 'elasticbeanstalk-us-east-2-109831127073'
  bucket_path: 'docker-frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
