sudo: required
services:
  - docker

before_install:
  - docker build -t faisaldev79/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true faisaldev79/frontend-react npm run test -- --coverage
